require('dotenv').config();
require('./config/database');

const Category = require('./models/category');
const Item = require('./models/item');

(async function() {
    
    await Category.deleteMany({});
    const categories = await Category.create([
        {name: 'Shrimps', sortOrder: 10},
        {name: 'Crab and Lobster', sortOrder: 20},
        {name: 'Fish', sortOrder: 30},
        {name: 'Shell Fish', sortOrder: 40},
        {name: 'Snake', sortOrder: 50},
        {name: 'Insects', sortOrder: 60},
        {name: 'Hot Pot', sortOrder: 70},
        {name: 'Beef', sortOrder: 80},
        {name: 'Pork and Chicken', sortOrder: 90},
        {name: 'Vegetable', sortOrder: 100},
        {name: 'Snacks and Appetizers', sortOrder: 110}
    ]);

    await Item.deleteMany({});
    const items = await Item.create([
        {name: 'Steam Live Metapenaeus Ensis', category: categories[0], 
        description: 'Steam live Metapenaeus Ensis prawns dip in sauce of your choice', price: '$19.99 per lb'},
        {name: 'Steam Live Blue Crab', category: categories[1], description: 'Steam whole live blue crab serve with garlic ginger sauce',
        price: '$7.99 per lb'},
        {name: 'Steam Live Manila Clams', category: categories[3], description: 'Steam live manila clams', price: '$5.99 per lb'},
        {name: 'Steam Live Mussels', category: categories[3], description: 'Steam live mussels', price: '$4.99 per lb'},
        {name: 'Steam Whole Live Scallop', category: categories[3], description: 'Steam whole live scallop with shell serve with chilli soy sauce', 
        price: '$9.99 each'},
        {name: 'Geoduck Sashimi', category: categories[3], description: 'Live Geoduck thin sliced sashimi', price: '$17.99 per lb'},
        {name: 'Japanese A5 Wagyu New York Strip Loin Roast', category: categories[7], description: 'Japanese A5 wagyu teppanyaki or shabu shabu', 
        price: '$81.99 per lb'},
        {name: 'Whole Maine Lobster and Beef Noodle Soup', category: categories[1], description: 'Whole live Maine lobster serve in beef broth with noodle', 
        price: '$79 per bowl'},
        {name: 'Chilli Pepper Live Snail', category: categories[3], description: 'Chilli pepper stir fry live snails extra spicy', 
        price: '$8.99 per lb'},
        {name: 'Deep Fried Baby pigeon', category: categories[8], description: '3 weeks old baby pigeon deep fried extra crispy skin', 
        price: '$13.99 each'},
        {name: 'Fanny Bay Oyster on Half Shell', category: categories[3], description: 'Fresh catch Fanny Bay oyster serve with lemon and cocktail sauce', 
        price: '$2.50 each'},
        {name : 'Smoked Salmon', category: categories[2], description: 'Red King salmon is baptized in our secret brine, then slowly smoked over alderwood coals', 
        price: '$13.99'},
        {name: 'Pig Brain', category: categories[6], description: 'Fresh pig brain for hot pot', price: '$7.99'},
        {name: 'Live Australian Lobster', category: categories[1], description: 'Garlic butter bake whole Australian Lobster', price: '$35 per lb'},
        {name: 'Mixed of Beef Organs', category: categories[7], description: 'A mixture of different beef organs in house secret sauce', 
        price: '$2.50 each skewer'},
        {name: 'Shark Fin Soup Chinese Style', category: categories[2], description: 'Shark fin served in chicken broth with oyster and crab meat', 
        price: '$9.99 per bowl'},
        {name: 'Live Asian Swamp Eel claypot', category: categories[2], description: 'Whole live swamp eel served in sizzling claypot', 
        price: '$12.99'},
        {name: 'Live River Shrimp and Seafood Soup', category: categories[0], description: 'Live fresh water shrimps with squid and mussel in seafood broth', 
        price: '$9.99'},
        {name: 'Vietnamese Mango Salad', category: categories[10], description: 'Grilled shrimps mango salad', price: '$12.99'},
        {name: 'Royal Chicken', category: categories[8], description: 'Mouantin free range running chicken', price: '$9.99 half chicken'},
        {name: 'Chinese Broccoli with Squid', category: categories[3], description: 'Aged dried squid legs stir fry chinese broccoli', 
        price: '$7.99'},
        {name: 'Beef Carpaccio', category: categories[7], description: 'Raw filet magnon served with quail egg, fried shallot dressed with house special sauce and lime juice', 
        price: '$17'},
        {name: 'Lemongrass Fried Tofu', catgory: categories[9], description: 'Deep fried tofu with lemongrass', price: '12'},
        {name: 'Giant River Prawns', category: categories[0], description: 'Savory butter garlic chilly sauce giant river prawns served with woven noodle', 
        price: '$11 each prawn'},
        {name: 'Banh Hoi Deluxe', category: categories[8], description: 'Grilled pork sausage, sugarcane shrimp, imperial roll, crispy pork belly served with woven noodle', 
        price: '$40 4-item combo'},
        {name: 'Razor Clam', category: categories[3], description: 'Live razor clam steam with garlic or stir fry with black bean sauce', 
        price: '$9.99 per lb'},
        {name: 'Hemifusus AKA Giant Sea Snail', category: categories[3], description: 'Live giant sea snail sashimi', 
        price: '$9.99 per lb'},
        {name: 'Steam Live Coral Spot Prawn', category: categories[0], description: 'Steam live coral spot prawn serve with chilli soy sauce', 
        price: '$29.99 per lb'},
        {name: 'Steam Fresh Oyster', category: categories[3], description: 'Steam fresh oyster with minced garlic', 
        price: '1,99 each'},
        {name: 'Steam Pork Spare Rib', category: categories[8], description: 'Steam pork spare ribs with vermicelli and melon in black bean sauce', 
        price: '$7.99'},
        {name: 'Vietnamese Egg Crab', category: categories[1], description: 'Steam live Vietnamese egg crab', 
        price: '$22.99 a lb'},
        {name: 'Roast Rack of Lamb', category: categories[7], description: 'Roast whole rack of lamb', 
        price: '$29.99'},
        {name: 'Santa Barbara Uni', category: categories[3], description: 'Fresh catch Santa Barbara uni', 
        price: '$29.99'},
        {name: 'Steam Live Marbled Rockfish', category: categories[2], description: 'Steam whole live marbled rockfish in soy sauce',
        price: '$12.99 per lb'},
        {name: 'Hokkaido Scallop', category: categories[3], description: 'Fresh Hokkaido scallop sashimi', price: '$4.99 a pc'},
        {name: 'Babylonia Lutosa', category: categories[3], description: 'Steam sea snail dipped in soy sauce', 
        price: '$19.99 a lb'},
        {name: 'Black Pepper Baked Crab', category: categories[1], description: 'Live California dungeness crab baked in grounded black pepper and butter', 
        price: '$6.99 per lb'},
        {name: 'Whole Maine Lobster', category: categories[1], description: 'Live Maine lobster can be served garlic butter baked or steam', 
        price: '$7.99 per lb'},
        {name: 'Salmon', category: categories[2], description: 'Fresh salmon sashimi style', price: '$13 for 5 pcs'},
        {name: 'Halibut', category: categories[2], description: 'Fresh halibut sashimi style', price: '$17 for 10 pcs'},
        {name: 'Cherry Stone Clam', category: categories[3], description: 'Fresh cherry stone clam on half shell', 
        price: '$2 each'},
        {name: 'Fried Stinky Tofu', category: categories[9], description: 'Deep fried aged stinky tofu', price: '$2'},
        {name: 'Octopus and Pig Intestine', category: categories[3], description: 'Octopus and pig intestine marinated in house special sauce', 
        price: '$2 each skewer'},
        
    ])
})